---
- name: Create user and add to sudo group
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: "username"
      prompt: "Enter username"
      private: False

    - name: "password"
      prompt: "Enter password"
      encrypt: "sha512_crypt"
      private: True

  tasks:
    - name: Ensure sudo group present
      group:
        name: sudo
        state: present
     
    - name: Create new user; added to sudo group
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present
        groups: sudo
        append: True
        create_home: True
        shell: /bin/bash
