---
- name: Check for updates
  hosts: all
  gather_facts: False
  tasks:
    - name: apt update
      become: True
      apt:
        update-cache: True
    
    - name: apt dist-upgrade
      become: True
      apt:
        upgrade: dist
      check_mode: True
      register: upgraded
    
    - name: Show upgraded
      debug:
        msg: "{{ upgraded }}"

    - name: Remove useless packages from the cache
      apt: 
        autoclean: True

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: True
      register: removed

    - name: Show removed dependencies
      debug:
        msg: "{{ removed }}"

