---
- name: Remove user(s)
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: False
  vars: 
    del_users:
      - dummy

  tasks:
  - name: Delete user(s)
    user:
      name: "{{ item }}"
      state: absent
      remove: True
    with_items: "{{ del_users }}"

  - name: Removing user(s) from sudoers
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: " {{ item }}"
      backup: yes
    with_items: "{{ del_users }}"
