---
- name: Running a few shell commands
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: False
  tasks:
  - name: Execute random comands as needed
    shell: |
      sudo ls -l /
      echo
      id
    register: out

  - debug:
      var: out.stdout_lines
