---
- name: Check firewall status
  hosts: all
  gather_facts: True
  tasks:
  - name: Check firewalld configuration
    shell: 'sudo firewall-cmd --list-all'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    register: f_out

  - name: Check ufw configuration
    shell: 'sudo ufw status'
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    register: u_out

  - name: Display firewalld configuration
    debug: 
      var: f_out.stdout_lines 
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Display ufw configuration
    debug: 
      var: u_out.stdout_lines 
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


  - name: Check iptables configuration - Ubuntu/Debian hosts only
    shell: 'iptables -L'
    register: ip_out
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: Display iptables configuration - Ubuntu/Debian hosts - inactive ufw
    debug:
      var: ip_out.stdout_lines
    when: >
     ( ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian') and
     ( u_out.stdout_lines is search("inactive") )


## if firewalld isn't running on Centos/Redhat host, investigate! ##

  #- name: Check nftables configuration - Centos/Redhat hosts only
    #shell: 'nft list ruleset'
    #register: nft_out
    #when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
#
  #- name: Display nftables configuration - Centos/Redhat hosts - inactive firewalld
    #debug:
      #var: nft_out.stdout_lines
    #when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
