---
- name: Check firewall status
  hosts: all
  gather_facts: True
  tasks:
  - shell: 'sudo firewall-cmd --list-all'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    register: out
  - shell: 'sudo ufw status'
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    register: out

  - debug: 
      var: out.stdout_lines 
