---
- name: Add new group
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: "group"
      prompt: "Enter group to add"
      private: False

  tasks:
    - name: Ensure sudo group present
      group:
        name: "{{ group }}"
        state: present
