---
# Sudo Group Setup
- name: Make sure we have the adm group
  group:
    name: adm
    state: present
 
- name: Make sure we have the sudo group
  group:
    name: sudo
    state: present
 
# User 
- name: Create new regular user with adm and sudo group
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    groups: adm,sudo
    append: True
    create_home: True
    shell: /bin/bash
