---
- name: Remove everything to do with snap
  hosts: all
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  tasks:
  - name: Get list of snaps currently running - excluding snapd or core
    shell: |
      sudo snap list | awk '!/Name/ && !/snapd/ && !/core/ {print $1}' | sort -r 
    register: snaps_found 

  #- debug:
      ##var: snaps_found.stdout_lines
      #msg: "{{ snaps_found.stdout }}"
      #msg: "{{ snaps_found.stdout_lines }}"

  - name: Remove snap
    snap:
      name: "{{ item }}"
      state: absent
    loop: "{{ snaps_found.stdout_lines }}"
    when: snaps_found.stdout | length > 0

  - name: Stop snapd process
    systemd:
      name: snapd
      scope: system
      state: stopped
    when: snaps_found.stdout | length > 0

  - name: Apt purge snapd package
    apt:
      name: snapd
      state: absent
      purge: yes
    when: snaps_found.stdout | length > 0


  - name: Apt purge avahi, whoopsie, apport, openvpn package
    apt:
      name: 
        - avahi-daemon
        - avahi-utils
        - whoopsie
        - apport
        - openvpn
      state: absent
      purge: yes

  - name: Apt autoclean and autoremove
    apt:
      autoremove: yes
      autoclean: yes
    when: snaps_found.stdout | length > 0

  - name: Prevent evolution-addressbook-factory from launching
    file:
      path: /usr/libexec/evolution-addressbook-factory
      owner: root
      group: root
      mode: 0644

  - name: Prevent evolution-calendar-factory from launching in backgroud
    file:
      path: /usr/libexec/evolution-calendar-factory
      owner: root
      group: root
      mode: 0644

  - name: Prevent evolution-data-server/evolution-alarm-notify from launching in backgroud
    file:
      path: /usr/libexec/evolution-data-server/evolution-alarm-notify
      owner: root
      group: root
      mode: 0644

  - name: Prevent evolution-source-registry from launching in backgroud
    file:
      path: /usr/libexec/evolution-source-registry
      owner: root
      group: root
      mode: 0644
