---
- name: Remove everything to do with snap
  hosts: all
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  tasks:
  - name: Get list of snaps currently running - excluding snapd
    shell: |
      sudo snap list | awk '!/Name/ && !/snapd/ {print $1}' | sort -r 
    register: snaps_found 

  #- debug:
      #var: snaps_found.stdout_lines
      #msg: "{{ snaps_found.stdout }}"
      #msg: "{{ snaps_found.stdout_lines }}"

  - name: Remove snaps
    snap:
      name: "{{ item }}"
      state: absent
    loop: "{{ snaps_found.stdout_lines }}"
  
# to add kill process and purge
