---
- name: Remove everything to do with snap
  hosts: all
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  tasks:
  - name: Get list of snaps currently running - excluding snapd or core
    shell: |
      sudo snap list | awk '!/Name/ && !/snapd/ && !/core/ {print $1}' | sort -r 
    register: snaps_found 

  #- debug:
      ##var: snaps_found.stdout_lines
      #msg: "{{ snaps_found.stdout }}"
      #msg: "{{ snaps_found.stdout_lines }}"

  - name: Remove snap
    snap:
      name: "{{ item }}"
      state: absent
    loop: "{{ snaps_found.stdout_lines }}"
    when: snaps_found.stdout | length > 0

  - name: Stop snapd process
    systemd:
      name: snapd
      scope: system
      state: stopped
    when: snaps_found.stdout | length > 0

  - name: Apt purge snapd package
    apt:
      name: snapd
      state: absent
      purge: yes
    when: snaps_found.stdout | length > 0

  - name: Apt autoclean and autoremove
    apt:
      autoremove: yes
      autoclean: yes
    when: snaps_found.stdout | length > 0
