---
- name: Display selinux status from gather_facts
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True

  tasks:
  - name: selinux status
    debug:
      msg: "{{ ansible_selinux }}"

  - name: apparmor status
    debug:
      msg: "{{ ansible_apparmor }}"
