---
- name: Obtain list of user accounts
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True

  tasks:
  - name: Read accounts from database
    getent:
      database: passwd

  - set_fact:
      #users: "{{ getent_passwd | dict2items | json_query('[? contains(value, `/bin/bash`)].key') }}"
      users: "{{ getent_passwd | dict2items | json_query('[? contains(value, `/sbin/nologin`)].key') }}"
      users2: "{{ getent_passwd | dict2items | json_query('[? !(contains(value, `/usr/sbin/nologin`))].key') }}"

  - debug:
      msg: 
        - list of users {{ users }}
        - list of users2 {{ users2 }}
